#Package configuration

extension="littlehelper"
extensionname="Little Helper"
#folder_name=littlehelper
#site="fasterjoomla"

#jdir=/cygdrive/d/Servers/Dev/$site/public_html
#sourcedir=$jdir/modules/$folder_name
#destdir=/cygdrive/e/DeV/Joomla/$extension

webpage="http://www.fasterjoomla.com/en/extensions/joomla-little-helper"
download="http://www.fasterjoomla.com/en/download/little-helper"
jed="http://extensions.joomla.org/extensions/administration/admin-performance/24016"

VERSION=2.1.2
VERSION=2.1.3
VERSION=2.1.3
VERSION=2.1.3
